### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by iammosespaulr** [nikki93/cgame#2]
[ 22%] Built target gorilla
[ 36%] Built target glfw
[ 38%] Built target minilua
[ 43%] Built target buildvm
[ 51%] Built target libluajit
[ 74%] Built target chipmunk_static
[ 75%] Linking C executable cgame
ext/gorilla/bin/linux/Release/libgorilla.a(vorbisfile.c.o): In function `_ov_64_seek_lap':
vorbisfile.c:(.text+0x1308): undefined reference to `alloca'
vorbisfile.c:(.text+0x133a): undefined reference to `alloca'
ext/gorilla/bin/linux/Release/libgorilla.a(vorbisfile.c.o): In function `_ov_d_seek_lap':
vorbisfile.c:(.text+0x1da8): undefined reference to `alloca'
vorbisfile.c:(.text+0x1dda): undefined reference to `alloca'
ext/gorilla/bin/linux/Release/libgorilla.a(vorbisfile.c.o): In function `ov_crosslap':
vorbisfile.c:(.text+0x6ba6): undefined reference to `alloca'
ext/gorilla/bin/linux/Release/libgorilla.a(vorbisfile.c.o):vorbisfile.c:(.text+0x6c36): more undefined references to `alloca' follow
collect2: error: ld returned 1 exit status
CMakeFiles/cgame.dir/build.make:939: recipe for target 'cgame' failed
make[2]: *** [cgame] Error 1
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/cgame.dir/all' failed
make[1]: *** [CMakeFiles/cgame.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nikki93** [comment]
@iammosespaulr What platform are you building on?

**Comment by iammosespaulr** [comment]
@nikki93 Ubuntu 17 ... btw I’d really appreciate if you would consider replying to my question on your OS expo application :+1:

**Comment by nikki93** [comment]
@iammosespaulr re: OS -- i'm currently dev'ing that closed source while i decide the direction to take it in 🤔-- but there is a chance I'll post the source out, will update you!

And re: this issue -- could you run `make` with `VERBOSE=1` so we can see the compiler command line actual final linker commandline?

**Comment by nikki93** [comment]
@iammosespaulr finally got around to fixing this in https://github.com/nikki93/cgame/commit/d467d0f9fb3373139504e22150a9c57973f278a2 i think!
